knowledge_base_file_path: data/knowledge.txt
openai_model_name: gpt-3.5-turbo
temperature: 0.0
vector_store_dim: 1536
vector_store_metric: cosine
max_react_iterations: 5
k_memory_interactions: 5
knowledge_base_tool_notation:
  "name": "Knowledge Base"
  "description": "use when need to answer questions about following topics: PacificTech Robotics, Innovative IT company, Aquatic robots."
search_tool_notation:
  "name": "Search"
  "description": "use when you need to answer questions about current events or the current state of the world."
redirect_tool_notation:
  "name": "Redirect to human"
  "description": "use if you want to redirect/connect/transfer to human agent/assistant/consultant or if you can't answer the question."
redirect_to_human_msg: "{Redirect to human agent}"
